// <auto-generated />
using System;
using InvoicesChecker.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoicesChecker.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220328152724_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InvoicesChecker.Models.FACTUUR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AFLEVERDATUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTW_REGISTRATIE_NR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FACTUURDATUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FACTUURNUMMER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FACTUURREFERENTIENR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FACTUURREGELSId")
                        .HasColumnType("int");

                    b.Property<string>("FACTUURSOORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLN_AFLEVERADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLN_ENVELOP_ZELF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLN_FACTUURADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLN_KOPERADRES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLN_LEVERANCIER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GLN_PARTNER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceFileId")
                        .HasColumnType("int");

                    b.Property<string>("ORDERNR_AFNEMER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORDER_DATUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAKBONNUMMER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TESTINDICATOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VALUTA")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FACTUURREGELSId");

                    b.HasIndex("InvoiceFileId");

                    b.ToTable("FACTUUR");
                });

            modelBuilder.Entity("InvoicesChecker.Models.FACTUURREGEL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ARTIKELCODE_LEVERANCIER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ARTIKELOMSCHRIJVING")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BTWSOORT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EAN_ARTIKELCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FACTUURREGELSId")
                        .HasColumnType("int");

                    b.Property<string>("FACTUUR_AANTAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GELEVERD_AANTAL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NETTOBEDRAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIJS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRIJSEENHEID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FACTUURREGELSId");

                    b.ToTable("FACTUURREGEL");
                });

            modelBuilder.Entity("InvoicesChecker.Models.FACTUURREGELS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("FACTUURREGELS");
                });

            modelBuilder.Entity("InvoicesChecker.Models.InvoiceFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Client")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("InvoiceFiles");
                });

            modelBuilder.Entity("InvoicesChecker.Models.FACTUUR", b =>
                {
                    b.HasOne("InvoicesChecker.Models.FACTUURREGELS", "FACTUURREGELS")
                        .WithMany()
                        .HasForeignKey("FACTUURREGELSId");

                    b.HasOne("InvoicesChecker.Models.InvoiceFile", null)
                        .WithMany("FACTUUR")
                        .HasForeignKey("InvoiceFileId");

                    b.Navigation("FACTUURREGELS");
                });

            modelBuilder.Entity("InvoicesChecker.Models.FACTUURREGEL", b =>
                {
                    b.HasOne("InvoicesChecker.Models.FACTUURREGELS", null)
                        .WithMany("FACTUURREGEL")
                        .HasForeignKey("FACTUURREGELSId");
                });

            modelBuilder.Entity("InvoicesChecker.Models.FACTUURREGELS", b =>
                {
                    b.Navigation("FACTUURREGEL");
                });

            modelBuilder.Entity("InvoicesChecker.Models.InvoiceFile", b =>
                {
                    b.Navigation("FACTUUR");
                });
#pragma warning restore 612, 618
        }
    }
}
